### PR TITLE
Add test strategy for JupyterHub v3.1.1

### PR DESCRIPTION
**Pull request by Sheila-nk**
- removed matrix config for Python 3.6 since it reached [end of life](https://endoflife.date/python)
- added matrix config for Python 3.9 using JupyterHub 3.1.1
- added matrix config for Python 3.11 using JupyterHub 3.1.1

Reference #476

### CODE REVIEW

**Comment by Sheila-nk** [comment]
Ping @GeorgianaElena the tests are failing with these errors: 

`AttributeError: 'coroutine' object has no attribute 'run_sync'` and
`RuntimeWarning: coroutine 'io_loop' was never awaited`


Seems like they are still referencing the old `app` fixture from `JupyterHub`.

**Comment by Sheila-nk** [comment]
io_loop error

**Comment by Sheila-nk** [comment]
@GeorgianaElena Could the problem be the cached workflow dependencies?

**Comment by GeorgianaElena** [comment]
> Seems like they are still referencing the old app fixture from JupyterHub.

Yes, this is because the removal of the `io_loop` from tests was not yet released. So, the [latest `jupyterhub` version 3.1.1](https://github.com/jupyterhub/jupyterhub/releases/tag/3.1.1) doesn't have the changes in https://github.com/jupyterhub/jupyterhub/pull/4332.

> AttributeError: 'coroutine' object has no attribute 'run_sync' and
RuntimeWarning: coroutine 'io_loop' was never awaited

Hmm, I believe these errors come from somewhere else and I suspect the breaking change introduced in pytest-asyncio  0.19.0 https://pytest-asyncio.readthedocs.io/en/latest/reference/changelog.html#id10 which is defaulting the `asyncio_mode` to [strict](https://pytest-asyncio.readthedocs.io/en/latest/concepts.html#strict-mode). This, together with unreliabily adding the asyncio marker to tests and fixture might have caused the use of multiple events loop.

So, my suggestion would be to explicitly add the `asyncio_mode=auto` and remove any explicit asyncio test mark and see if this fixes it.

**Comment by Sheila-nk** [comment]
@GeorgianaElena the test strategies for `JupyterHub` v3.1.1 are passing as expected. There needs to be a fix for the `SQLAlchemy` compatibility issue for the other `JupyterHub` versions. I don't know whether I should focus on working on the compatibility issue: https://github.com/jupyterhub/dockerspawner/issues/478 or wait for this PR to be merged regardless so we can continue with testing the plugin.

**Comment by minrk** [comment]
@Sheila-nk for sqlalchemy, you should be able to add `slqalchemy==1.*` to your test environment requirements.

**Comment by Sheila-nk** [comment]
> @Sheila-nk for sqlalchemy, you should be able to add `slqalchemy==1.*` to your test environment requirements.

This worked. Thank you!

**Comment by Sheila-nk** [comment]
@minrk with restricting `sqlalchemy` to v1 in `dev-requirements.txt`, is that a complete solution to the compatibility issue, or is there more to be done?

**Comment by GeorgianaElena** [comment]
@Sheila-nk, I'd advocate not pinning `sqlalchemy` in `dev-requirements` in this PR.

I believe what @minrk suggested is to do experiment with thi pinning in https://github.com/jupyterhub/dockerspawner/pull/476 while integrating the pytest plugin to make sure it works. @minrk, can you please provide more details about this one?

@Sheila-nk, if you drop the commit pinning sqlalchemy, I'll be comfortable merging this PR. Additionally, I believe discussions about pinning or not pinning `sqlalchemy` to fix the tests, should happen in https://github.com/jupyterhub/dockerspawner/issues/478 for a more persistent context.

**Pull request merged**
