### PR TITLE
Changelog for 12.0

### LINKED ISSUE #366: Release a new version?
The last release was 12 months ago, with some bugfixes landing on master in the meantime (in particular #334 affects my deployment). Is there a plan to make a new (possibly bugfix) release?

### PR DESCRIPTION
**Pull request by minrk**
- [x] waiting for #412 at least

Highlights the breaking changes in run_as_root and container-name escaping.

Next version drops the leading 0, so planning to release 12.0 instead of 0.12.

closes #366

### CODE REVIEW

**Comment by consideRatio** [comment]
@minrk is the practice of promoting the minor version to be the major version an established thing to do in situations when about to start using the major version number?

**Review by GeorgianaElena — APPROVED** [review]
LGTM :rocket:

(going from `0.12` to `12.0` is new for me too :astonished:)

**Comment by minrk** [comment]
> If you can confirm that you really intended to release 12.0 rather than 0.12 or 1.0, then go for a merge!

It is intentional and I have done it before (on pyzmq), but I don't think it's common. I'm open to objections!

The idea is to get around the stress of "are we ready for 1.0?!" by skipping it entirely. 1.0 carries a lot of weight, but isn't really meaningful in practice. There is *lots* of software out there with a leading 0 that is mature and used widely in production, which generally means it shouldn't have a leading 0 anymore. But folks often worry too much about "what does 1.0 mean?" or adding a bunch of blockers such as "We need X and Y that we've been talking about for years before we can call it 1.0" so they end up sticking with 0.x for much longer than the maturity of the package suggests. There is even a perverse factor that the longer you wait to make 1.0, the *more* work it is to make a release that feels big enough to call it 1.0, when the opposite should be true. This strategy of "just drop the leading 0" is a way of communicating: **we are ready for general use, but this is also just the next release, not a special milestone**.

**Comment by consideRatio** [comment]
@minrk well thought out! :) Sounds good to me!

**Pull request merged**
