### PR TITLE
Switch default image to quay.io

### PR DESCRIPTION
**Pull request by yuvipanda**
Bump up a couple other versions in the Dockerfile examples as well.

Ref https://github.com/jupyterhub/team-compass/issues/688

### CODE REVIEW

**Comment by manics** [comment]
Tests are failing on this PR:
`docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=4&fromImage=quay.io%2Fjupyterhub%2Fsingleuser: Not Found ("manifest for quay.io/jupyterhub/singleuser:4 not found: manifest unknown: manifest unknown")`

**Comment by minrk** [comment]
Looks like the image migration is missing some tags (4 missing, only have 4.0)?

**Comment by yuvipanda** [comment]
Gotta tweak my regex! I will run that again shortly

**Comment by yuvipanda** [comment]
Just copied v4.0 now!

**Pull request merged**
