### PR TITLE
Lock dependency to docker as latest release has breaking changes.

### PR DESCRIPTION
**Pull request by ckbhatt**

### CODE REVIEW

**Comment by ckbhatt** [comment]
The latest thing that started breaking our setup was     c.DockerSpawner.extra_create_kwargs.update({'volume_driver': 'local'}) in our config.

**Comment by dhirschfeld** [comment]
Got a reference to the breaking changes affecting `DockerSpawner`?

Also, for reference do you have a traceback from `JupyterHub`?

**Comment by dhirschfeld** [comment]
I'm wondering if this is related to #192 but you haven't provided enough information for me to tell.

**Comment by ckbhatt** [comment]
`jupyterhub                  |     Traceback (most recent call last):
jupyterhub                  |       File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
jupyterhub                  |         result = yield result
jupyterhub                  |       File "/tmp-jh/jupyterhub/handlers/base.py", line 811, in get
jupyterhub                  |         raise copy.copy(exc).with_traceback(exc.__traceback__)
jupyterhub                  |       File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
jupyterhub                  |         result = yield result
jupyterhub                  |       File "/tmp-jh/jupyterhub/handlers/base.py", line 845, in get
jupyterhub                  |         yield self.spawn_single_user(current_user)
jupyterhub                  |       File "/tmp-jh/jupyterhub/handlers/base.py", line 570, in spawn_single_user
jupyterhub                  |         yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
jupyterhub                  |       File "/tmp-jh/jupyterhub/handlers/base.py", line 525, in finish_user_spawn
jupyterhub                  |         yield spawn_future
jupyterhub                  |       File "/tmp-jh/jupyterhub/user.py", line 439, in spawn
jupyterhub                  |         raise e
jupyterhub                  |       File "/tmp-jh/jupyterhub/user.py", line 378, in spawn
jupyterhub                  |         ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
jupyterhub                  |       File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 536, in start
jupyterhub                  |         resp = yield self.docker('create_container', **create_kwargs)
jupyterhub                  |       File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 398, in result
jupyterhub                  |         return self.__get_result()
jupyterhub                  |       File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
jupyterhub                  |         raise self._exception
jupyterhub                  |       File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 55, in run
jupyterhub                  |         result = self.fn(*self.args, **self.kwargs)
jupyterhub                  |       File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 409, in _docker
jupyterhub                  |         return m(*args, **kwargs)
jupyterhub                  |     TypeError: create_container() got an unexpected keyword argument 'volume_driver'`

**Comment by ckbhatt** [comment]
**Stacktrace from JH is below**

> Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/tmp-jh/jupyterhub/handlers/base.py", line 811, in get
    raise copy.copy(exc).with_traceback(exc.__traceback__)
  File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/tmp-jh/jupyterhub/handlers/base.py", line 845, in get
    yield self.spawn_single_user(current_user)
  File "/tmp-jh/jupyterhub/handlers/base.py", line 570, in spawn_single_user
    yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
  File "/tmp-jh/jupyterhub/handlers/base.py", line 525, in finish_user_spawn
    yield spawn_future
  File "/tmp-jh/jupyterhub/user.py", line 439, in spawn
    raise e
  File "/tmp-jh/jupyterhub/user.py", line 378, in spawn
    ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
  File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 536, in start
    resp = yield self.docker('create_container', **create_kwargs)
  File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 409, in _docker
    return m(*args, **kwargs)
TypeError: create_container() got an unexpected keyword argument 'volume_driver'

**Comment by radshio** [comment]
Docker 3.0 will work if you move `'volume-driver': 'local'` from `c.DockerSpawner.extra_create_kwargs.update` to `c.DockerSpawner.extra_host_config` .
See docker-py [change-log](https://github.com/docker/docker-py/commit/7fabcdaa4cbcf1c7905c2c2e7669a5a4ac594735#diff-deba20bc26bec174539e73b2f391fffaR22).
ie:
```
c.DockerSpawner.extra_host_config = {
        'network_mode': network_name,
        'volume_driver': 'local'
 }
```

**Comment by dhirschfeld** [comment]
Thanks for the extra info @radshio! 

Since it's a configuration issue I'm not sure the right answer is to pin `docker` in `DockerSpawner` itself.

Instead in your own environment you can simply specify `docker <3.0` so that your existing configuration will continue to work. In that way someone just setting up `DockerSpawner` with no existing configuration can use the latest and greatest `docker` release.

**Comment by minrk** [comment]
Closing since this is a change at the passthrough configuration level (i.e. user config must be aware of the docker version, not DockerSpawner), not related to DockerSpawner itself.

**Pull request closed without merging**
