### PR TITLE
Fixes Issue #90 and added code to normalize username substitution

### PR DESCRIPTION
**Pull request by whitead**
Added and tested code as suggested in Issue #90 discussion. Found additional issue with usernames that cannot be used as filenames when inserting them into volume labels. I added slugify code from Django framework to normalize usernames so they can be filenames.

### CODE REVIEW

**Comment by rgbkrk** [comment]
`slugify` looks quite testable - would you be able to add a test?

**Comment by whitead** [comment]
I mean, I guess if you want we can copy-pasta from [django](https://github.com/django/django/blob/ecb59cc6579402b68ddfd4499bf30edacf5963be/tests/template_tests/filter_tests/test_slugify.py). Do we need this?

**Comment by whitead** [comment]
Hmm, I noticed the tests weren't actually being run and my code breaks the only test there is. Let me update my PR. I'll also put the test scripts into the travis file for you.

**Comment by whitead** [comment]
Alright, I've written a new test, made the old ones pass, and put them into the `.travis.yml` file so they will be part of the CI.

**Comment by rgbkrk** [comment]
Now that was going the extra mile. Thank you!

**Comment by minrk** [comment]
Sorry, I missed this one. I think there are some issues with how slugify is being used. In particular, it's coercing valid, safe values without a mechanism to allow them, which could be problematic.

@whitead can you give an example of a username that was producing a volume-bind that doesn't work? Non-ascii values should be allowed, and case should probably be left alone, as well.

**Pull request merged**
