### PR TITLE
Make default name_template compatible with named servers.

### PR DESCRIPTION
**Pull request by danielballan**
As noted by @zeehio in [this comment](https://github.com/jupyterhub/dockerspawner/issues/257#issuecomment-492275806)
the default ``name_template`` is not compatible with using named servers. Should the default be updated?

The current docstring mentions backward compatibility. If
backward-compatibility of container names is very important, perhaps it would
be better to leave the default as is and simply mention ``{servername}`` in the
docstring and the README.

### CODE REVIEW

**Comment by danielballan** [comment]
Another possibility would be to make the default template

```
{prefix}-{username}{servername}
```

which means that the default (unnamed) server would create a container of the same name as before, retaining back-compat. The disadvantage, of course, is that the username runs right into the server name without a separator.

**Comment by minrk** [comment]
For compatibility, using a dynamic default should do it without breaking the default case:

```python
@default('name_template')
def _default_name_template(self):
    if self.name:
        return "{prefix}-{username}-{servername}"
    else:
        return "{prefix}-{username}"
```

**Comment by danielballan** [comment]
Oh, perfect. At the time I submitted this PR I hadn't yet discovered dynamic defaults. Really nice solution. Pushed.

**Comment by danielballan** [comment]
One of the three builds failed---see [build log](https://travis-ci.org/jupyterhub/dockerspawner/jobs/593527762?utm_medium=notification&utm_source=github_status). It looks like a transient failure to me.

**Comment by danielballan** [comment]
A friendly bump on this. Do you think the CI failures are real?

**Comment by manics** [comment]
I've closed/reopened to trigger an updated CI check

**Comment by GeorgianaElena** [comment]
The CI failures from now are definitely unrelated.
When @manics closed/reopened the PR, [the tests passed](https://travis-ci.org/github/jupyterhub/dockerspawner/builds/593527759), but I've restarted the build and now they [fail again because of a version conflict](https://travis-ci.org/github/jupyterhub/dockerspawner/builds/698951135).

I believe this LGTM :tada: What do you think, @manics?

**Comment by manics** [comment]
Thanks @danielballan , sorry for the delay in getting this merged

**Comment by danielballan** [comment]
Not a problem! Thanks for your work on maintaining JupyterHub!

**Pull request merged**
